version: "3"
services:
    web:
        image: daocloud.io/farseer810/docker_demo:1.0-8ba8289
        deploy:
            replicas: 20
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "10000:8080"
        networks:
            - webnet

networks:
    webnet:
